import { chromium } from "@playwright/test"
const b = await chromium.launch(); const p = await b.newPage({ viewport: { width: 1440, height: 900 } })
const errors = []; p.on("pageerror", (e) => errors.push(e.message.slice(0, 120)))
await p.route("**/api/**", async (route) => { await new Promise((r) => setTimeout(r, 1200)); await route.continue() })
await p.goto("http://localhost:3300/login"); await p.waitForTimeout(1500)
await p.getByRole("button", { name: "Enter as teacher" }).click()
await p.waitForSelector("text=Where the class stands", { timeout: 20000 }); await p.waitForTimeout(3000)
await p.click("nav >> text=Activities")
await p.waitForSelector("[aria-busy]", { timeout: 5000 })
console.log("activities: skeleton shown, list items visible during load:", await p.locator("a[href^='/activities/']").count())
await p.waitForSelector("a[href^='/activities/']", { timeout: 20000 })
await p.click("nav >> text=Overview")
await p.waitForSelector("[aria-busy]", { timeout: 5000 })
console.log("back to overview: skeleton, cached heatmap initials:", await p.locator("a[href^='/students/']").count())
await p.waitForSelector("text=Where the class stands", { timeout: 20000 }); await p.waitForTimeout(2500)
await p.selectOption("header select", { label: "8º ano A" })
await p.waitForSelector("[aria-busy]", { timeout: 5000 })
console.log("class switch: skeleton, previous class initials:", await p.locator("a[href^='/students/']").count())
await p.waitForTimeout(4500)
console.log("8A loaded, initials:", await p.locator("a[href^='/students/']").count(), "| errors:", errors.length ? errors : "none")
await b.close()
